
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SS.Models
{

using System;
    using System.Collections.Generic;

    public partial class ACCOMMODATIONS
    {

        public ACCOMMODATIONS()
        {

            this.TENNANTS = new HashSet<TENNANTS>();

            this.BILLS = new HashSet<BILLS>();

            this.REQUISITION_PROPERTY_MAPPINGS = new HashSet<REQUISITION_PROPERTY_MAPPINGS>();

        }


        public System.Guid ID { get; set; }

        public string STREET_ADDRESS { get; set; }

        public string CITY { get; set; }

        public string PARISH { get; set; }

        public string LATITUE { get; set; }

        public string LOGITUDE { get; set; }

        public decimal PRICE { get; set; }

        public decimal SECURITY_DEPOSIT { get; set; }

        public short OCCUPANCY { get; set; }

        public string GENDER_PREFERENCE { get; set; }

        public string DESCRIPTION { get; set; }

        public bool WATER { get; set; }

        public bool ELECTRICITY { get; set; }

        public bool CABLE { get; set; }

        public bool GAS { get; set; }

        public bool INTERNET { get; set; }

        public bool AVAILABILITY { get; set; }

        public string ENROLMENT_KEY { get; set; }

        public string TERMS_AGREEMENT { get; set; }

        public System.Guid OWNER { get; set; }

        public bool IS_STUDENT_ACC { get; set; }

        public short HOUSE_BATHROOM_AMOUNT { get; set; }

        public Nullable<System.DateTime> DATE_ADDED { get; set; }

        public string IMAGE_URL { get; set; }

        public System.Web.Mvc.SelectListItem[] Parishes { get;set;}



    public virtual ICollection<TENNANTS> TENNANTS { get; set; }

    public virtual ICollection<BILLS> BILLS { get; set; }

    public virtual ICollection<REQUISITION_PROPERTY_MAPPINGS> REQUISITION_PROPERTY_MAPPINGS { get; set; }

    public virtual LANDLORDS LANDLORDS { get; set; }

}

}
