//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLS
    {
        public System.Guid ID { get; set; }
        public string B_TYPE { get; set; }
        public decimal B_AMOUNT { get; set; }
        public string DESCRIPTION { get; set; }
        public System.DateTime DATE_ISSUED { get; set; }
        public System.DateTime DATE_DUE { get; set; }
        public string BILL_URL { get; set; }
        public System.Guid ACCOMMODATION_ID { get; set; }
    
        public virtual ACCOMMODATIONS ACCOMMODATIONS { get; set; }
    }
}
