//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public System.Guid ID { get; set; }
        public System.Guid OwnerID { get; set; }
        public System.Guid PropertyID { get; set; }
        public System.Guid TennantID { get; set; }
        public string TypeCode { get; set; }
        public decimal AmtDue { get; set; }
        public bool IsPaid { get; set; }
        public string BillURL { get; set; }
        public System.DateTime DateDue { get; set; }
        public System.DateTime DateTCreated { get; set; }
    
        public virtual Owner Owner { get; set; }
        public virtual Property Property { get; set; }
        public virtual Tennant Tennant { get; set; }
        public virtual BillType BillType { get; set; }
    }
}
