
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class COMPLAINTS
{

    public System.Guid ID { get; set; }

    public System.Guid COMPLAINER_ID { get; set; }

    public string COMPLAINT { get; set; }

    public System.DateTime C_DATE { get; set; }

    public System.TimeSpan C_TIME { get; set; }

}

}
