//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EasyFindPropertiesEntities : DbContext
    {
        public EasyFindPropertiesEntities()
            : base("name=EasyFindPropertiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdPriority> AdPriority { get; set; }
        public virtual DbSet<AdType> AdType { get; set; }
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<BillType> BillType { get; set; }
        public virtual DbSet<Complaint> Complaint { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<PropertyCategory> PropertyCategory { get; set; }
        public virtual DbSet<PropertyCondition> PropertyCondition { get; set; }
        public virtual DbSet<PropertyImage> PropertyImage { get; set; }
        public virtual DbSet<PropertyPurpose> PropertyPurpose { get; set; }
        public virtual DbSet<PropertyRating> PropertyRating { get; set; }
        public virtual DbSet<PropertyRequisition> PropertyRequisition { get; set; }
        public virtual DbSet<PropertyType> PropertyType { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<SubscriptionType> SubscriptionType { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<TagType> TagType { get; set; }
        public virtual DbSet<Tennant> Tennant { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<UserTypeAssoc> UserTypeAssoc { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<MessageTrash> MessageTrash { get; set; }
        public virtual DbSet<MeetingMembers> MeetingMembers { get; set; }
        public virtual DbSet<Meeting> Meeting { get; set; }
        public virtual DbSet<SavedProperties> SavedProperties { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }
        public virtual DbSet<SubscriptionExtension> SubscriptionExtension { get; set; }
        public virtual DbSet<Division> Division { get; set; }
        public virtual DbSet<PasswordRecoveryRequest> PasswordRecoveryRequest { get; set; }
    
        public virtual int Sp_UpdatePropertiesAvailability()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UpdatePropertiesAvailability");
        }
    }
}
