//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyFindPropertiesEntities : DbContext
    {
        public EasyFindPropertiesEntities()
            : base("name=EasyFindPropertiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdPriority> AdPriority { get; set; }
        public virtual DbSet<AdType> AdType { get; set; }
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<BillType> BillType { get; set; }
        public virtual DbSet<Complaint> Complaint { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<PropertyCategory> PropertyCategory { get; set; }
        public virtual DbSet<PropertyCondition> PropertyCondition { get; set; }
        public virtual DbSet<PropertyImage> PropertyImage { get; set; }
        public virtual DbSet<PropertyPurpose> PropertyPurpose { get; set; }
        public virtual DbSet<PropertyRating> PropertyRating { get; set; }
        public virtual DbSet<PropertyRequisition> PropertyRequisition { get; set; }
        public virtual DbSet<PropertyType> PropertyType { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<SubscriptionType> SubscriptionType { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<TagType> TagType { get; set; }
        public virtual DbSet<Tennant> Tennant { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<UserTypeAssoc> UserTypeAssoc { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Message> Message { get; set; }
    }
}
