
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SS.Models
{

    using System;
    using System.Collections.Generic;

    public partial class HOUSE
    {

        public HOUSE()
        {

            this.REQUISITION_PROPERTY_MAPPINGS = new HashSet<REQUISITION_PROPERTY_MAPPINGS>();

        }


        public System.Guid ID { get; set; }

        public string STREET_ADDRESS { get; set; }

        public string CITY { get; set; }

        public string PARISH { get; set; }

        public decimal PRICE { get; set; }

        public string BED_ROOM_AMOUNT { get; set; }

        public string LIVING_ROOM_AMOUNT { get; set; }

        public string BATH_ROOM_AMOUNT { get; set; }

        public string PURPOSE { get; set; }

        public bool ISFURNISHED { get; set; }

        public string DESCRIPTION { get; set; }

        public string IMAGE_URL { get; set; }

        public System.Guid OWNER { get; set; }

        public Nullable<System.DateTime> DATE_ADDED { get; set; }

        public System.Web.Mvc.SelectListItem[] Parishes { get; set; }


        public virtual ICollection<REQUISITION_PROPERTY_MAPPINGS> REQUISITION_PROPERTY_MAPPINGS { get; set; }

        public virtual LANDLORDS LANDLORDS { get; set; }

    }

}
