//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LANDLORDS
    {
        public LANDLORDS()
        {
            this.ACCOMMODATIONS = new HashSet<ACCOMMODATIONS>();
            this.HOUSE = new HashSet<HOUSE>();
            this.LAND = new HashSet<LAND>();
            this.MEETINGS = new HashSet<MEETINGS>();
            this.SUBSCRIPTIONS = new HashSet<SUBSCRIPTIONS>();
        }
    
        public System.Guid ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string GENDER { get; set; }
        public string CELL { get; set; }
        public string EMAIL { get; set; }
        public string PICTURE_URL { get; set; }
        public string PASSWORD { get; set; }
        public string PASSWORD_CONFIRMED { get; set; }

        public virtual ICollection<ACCOMMODATIONS> ACCOMMODATIONS { get; set; }
        public virtual ICollection<HOUSE> HOUSE { get; set; }
        public virtual ICollection<LAND> LAND { get; set; }
        public virtual ICollection<MEETINGS> MEETINGS { get; set; }
        public virtual ICollection<SUBSCRIPTIONS> SUBSCRIPTIONS { get; set; }
    }
}
