//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public System.Guid ID { get; set; }
        public System.Guid OwnerID { get; set; }
        public System.Guid RequesteeId { get; set; }
        public string Location { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public System.TimeSpan MeetingTime { get; set; }
        public string Purpose { get; set; }
        public System.DateTime DateTCreated { get; set; }
    
        public virtual Owner Owner { get; set; }
        public virtual MeetingRequisition MeetingRequisition { get; set; }
    }
}
