
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MEETINGS
{

    public System.Guid ID { get; set; }

    public System.Guid LANDLORD_ID { get; set; }

    public string LOCATION { get; set; }

    public System.DateTime M_DATE { get; set; }

    public System.TimeSpan M_TIME { get; set; }



    public virtual LANDLORDS LANDLORDS { get; set; }

}

}
