//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meeting()
        {
            this.MeetingMembers = new HashSet<MeetingMembers>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid InviterUserID { get; set; }
        public string Location { get; set; }
        public string MeetingTitle { get; set; }
        public System.DateTime MeetingDate { get; set; }
        public System.TimeSpan MeetingTime { get; set; }
        public string Purpose { get; set; }
        public System.DateTime DateTCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeetingMembers> MeetingMembers { get; set; }
        public virtual User User { get; set; }
    }
}
