//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingMembers
    {
        public System.Guid MeetingID { get; set; }
        public System.Guid InviteesUserID { get; set; }
        public System.DateTime DateTCreated { get; set; }
    
        public virtual User User { get; set; }
        public virtual Meeting Meeting { get; set; }
    }
}
