//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGES
    {
        public System.Guid ID { get; set; }
        public System.Guid MESSENGER_ID { get; set; }
        public System.Guid RECIPIENT_ID { get; set; }
        public string MESSAGE { get; set; }
        public System.DateTime DATE { get; set; }
    }
}
