//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordRecoveryRequest
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public string AccessCode { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public System.DateTime DateTCreated { get; set; }
        public bool Processed { get; set; }
        public Nullable<System.DateTime> DateTModified { get; set; }
    
        public virtual User User { get; set; }
    }
}
