//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.SubscriptionExtension = new HashSet<SubscriptionExtension>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid SubscriptionID { get; set; }
        public string PaymentMethodID { get; set; }
        public decimal Amount { get; set; }
        public string VoucherNumber { get; set; }
        public bool IsVerified { get; set; }
        public Nullable<System.DateTime> DateTModified { get; set; }
        public System.DateTime DateTCreated { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Subscription Subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionExtension> SubscriptionExtension { get; set; }
    }
}
