//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Bill = new HashSet<Bill>();
            this.Complaint = new HashSet<Complaint>();
            this.PropertyImage = new HashSet<PropertyImage>();
            this.PropertyRating = new HashSet<PropertyRating>();
            this.PropertyRequisition = new HashSet<PropertyRequisition>();
            this.Tags = new HashSet<Tags>();
            this.Tennant = new HashSet<Tennant>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid OwnerID { get; set; }
        public string Title { get; set; }
        public string PurposeCode { get; set; }
        public System.Guid TypeID { get; set; }
        public string AdTypeCode { get; set; }
        public string AdPriorityCode { get; set; }
        public string ConditionCode { get; set; }
        public string CategoryCode { get; set; }
        public string StreetAddress { get; set; }
        public string Division { get; set; }
        public string Community { get; set; }
        public string NearByEstablishment { get; set; }
        public string Country { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string NearByEstablishmentLng { get; set; }
        public string NearByEstablishmentLat { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> SecurityDeposit { get; set; }
        public Nullable<int> Occupancy { get; set; }
        public string GenderPreferenceCode { get; set; }
        public string Description { get; set; }
        public bool Availability { get; set; }
        public string EnrolmentKey { get; set; }
        public string TermsAgreement { get; set; }
        public Nullable<int> TotAvailableBathroom { get; set; }
        public Nullable<int> TotRooms { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<bool> IsReviewable { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateTModified { get; set; }
        public System.DateTime DateTCreated { get; set; }
        public string StreetNumber { get; set; }
    
        public virtual AdPriority AdPriority { get; set; }
        public virtual AdType AdType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint> Complaint { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual PropertyCategory PropertyCategory { get; set; }
        public virtual PropertyCondition PropertyCondition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyImage> PropertyImage { get; set; }
        public virtual PropertyPurpose PropertyPurpose { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRating> PropertyRating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyRequisition> PropertyRequisition { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tags> Tags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tennant> Tennant { get; set; }
    }
}
