//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUISITIONS
    {
        public System.Guid REQUISITION_ID { get; set; }
        public System.DateTime R_DATE { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string EMAIL { get; set; }
        public string CELL { get; set; }
        public bool ACCEPTED { get; set; }
        public string GENDER { get; set; }
    
        public virtual REQUISITION_PROPERTY_MAPPINGS REQUISITION_PROPERTY_MAPPINGS { get; set; }
    }
}
