
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class REQUISITION_PROPERTY_MAPPINGS
{

    public System.Guid ID { get; set; }

    public Nullable<System.Guid> ACCOMMODATION_ID { get; set; }

    public Nullable<System.Guid> HOUSE_ID { get; set; }

    public Nullable<System.Guid> LAND_ID { get; set; }



    public virtual ACCOMMODATIONS ACCOMMODATIONS { get; set; }

    public virtual HOUSE HOUSE { get; set; }

    public virtual REQUISITIONS REQUISITIONS { get; set; }

    public virtual LAND LAND { get; set; }

}

}
