//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public System.Guid ID { get; set; }
        public System.Guid OwnerID { get; set; }
        public string TypeCode { get; set; }
        public int Period { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateTModified { get; set; }
        public System.DateTime DateTCreated { get; set; }
    
        public virtual Owner Owner { get; set; }
        public virtual SubscriptionType SubscriptionType { get; set; }
    }
}
