//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tags
    {
        public System.Guid ID { get; set; }
        public System.Guid PropertyID { get; set; }
        public System.Guid TypeID { get; set; }
        public System.DateTime DateTCreated { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual TagType TagType { get; set; }
    }
}
