
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SS.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TENNANTS
{

    public System.Guid ID { get; set; }

    public System.DateTime DOB { get; set; }

    public string FIRST_NAME { get; set; }

    public string MIDDLE_NAME { get; set; }

    public string LAST_NAME { get; set; }

    public string GENDER { get; set; }

    public string STREET_ADDRESS { get; set; }

    public string CITY { get; set; }

    public string PARISH { get; set; }

    public string CELL { get; set; }

    public string EMAIL { get; set; }

    public string UNIVERSITY { get; set; }

    public string PROGRAMME_NAME { get; set; }

    public Nullable<System.DateTime> PROGRAMME_START_DATE { get; set; }

    public Nullable<System.DateTime> PROGRAMME_END_DATE { get; set; }

    public Nullable<short> SETTLEMENT_PERIOD { get; set; }

    public string DESCRIPTION { get; set; }

    public string PICTURE_URL { get; set; }

    public System.Guid ACCOMMODATION_ID { get; set; }



    public virtual ACCOMMODATIONS ACCOMMODATIONS { get; set; }

}

}
